<?php

namespace IATBundle\Entity;

/**
 * DealFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealFilesRepository extends \Doctrine\ORM\EntityRepository
{
	
	/**
	 * @author Ashish Shah (ashish414@gmail.com)
	 *
	 * Description : This function is used to get latest uploaded deal file
	 *
	 * @param 1 : $userId
	 *
	 * @return : deal inquiries
	 *
	 * @throws Exception: Null
	 *
	 **/
	public function getLatestUploadedFile(){
		$dealFile = $this->createQueryBuilder('df')
			->orderBy('df.id', 'DESC')
			->setMaxResults(1)
			->getQuery()
			->getOneOrNullResult();
		return $dealFile->getFileName();
	}
}
